:connect SQLFCI02\DR
ALTER DATABASE [AGDB01] SET HADR OFF;
ALTER DATABASE [AGDB02] SET HADR OFF;
GO

:connect SQLFCI01
--ALTER AVAILABILITY GROUP [AlwaysONAG01]
--REMOVE LISTENER N'SQLAG01';
DROP AVAILABILITY GROUP [AlwaysOnAG01];
GO

:connect SQLFCI02\DR
DROP DATABASE [AGDB01];
DROP DATABASE [AGDB02];
GO

:connect SQLFCI01
DROP DATABASE [AGDB01];
DROP DATABASE [AGDB02];
GO

!!rd "\\SQLFCI02\D$\MSSQL12.MSSQLSERVER" /Q /S
!!rd "\\SQLFCI02\L$\MSSQL12.MSSQLSERVER" /Q /S

:Connect SQLFCI01
IF (SELECT state FROM sys.endpoints WHERE name = N'Hadr_endpoint') <> 0
BEGIN
	DROP ENDPOINT [Hadr_endpoint];
END

:Connect SQLFCI02\DR
IF (SELECT state FROM sys.endpoints WHERE name = N'Hadr_endpoint') <> 0
BEGIN
	DROP ENDPOINT [Hadr_endpoint];
END
