-- Event Session DDL autogenerated using ConvertTraceToExtendedEvent procedure.
-- (c) 2009 Microsoft Corporation.
CREATE EVENT SESSION XE_DefaultTemplateTrace
ON SERVER
ADD EVENT sqlserver.database_file_size_change
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_server_principal_name)
WHERE 
)
,
ADD EVENT sqlserver.database_mirroring_state_change
(ACTION (sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_server_principal_name, sqlserver.transaction_id)
WHERE 
)
,
ADD EVENT sqlserver.errorlog_written
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_server_principal_name, sqlserver.transaction_id)
WHERE 
)
,
ADD EVENT sqlserver.full_text_crawl_started
(ACTION (sqlserver.database_id, sqlserver.event_sequence, sqlserver.is_system, sqlserver.server_instance_name, sqlserver.session_id, sqlserver.session_server_principal_name, sqlserver.transaction_id)
WHERE 
)
,
ADD EVENT sqlserver.full_text_crawl_stopped
(ACTION (sqlserver.database_id, sqlserver.event_sequence, sqlserver.is_system, sqlserver.server_instance_name, sqlserver.session_id, sqlserver.session_server_principal_name, sqlserver.transaction_id)
WHERE 
)
,
ADD EVENT sqlserver.hash_warning
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_resource_group_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
,
ADD EVENT sqlserver.missing_column_statistics
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_resource_group_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
,
ADD EVENT sqlserver.missing_join_predicate
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_resource_group_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
,
ADD EVENT sqlserver.object_altered
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_resource_group_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
,
ADD EVENT sqlserver.object_created
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_resource_group_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
,
ADD EVENT sqlserver.object_deleted
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_resource_group_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
,
ADD EVENT sqlserver.plan_guide_unsuccessful
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
,
ADD EVENT sqlserver.server_memory_change
(ACTION (sqlserver.event_sequence, sqlserver.is_system, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.session_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
,
ADD EVENT sqlserver.server_start_stop
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_server_principal_name)
WHERE 
)
,
ADD EVENT sqlserver.sort_warning
(ACTION (sqlserver.client_app_name, sqlserver.client_hostname, sqlserver.client_pid, sqlserver.database_id, sqlserver.database_name, sqlserver.event_sequence, sqlserver.is_system, sqlserver.nt_username, sqlserver.request_id, sqlserver.server_instance_name, sqlserver.server_principal_name, sqlserver.server_principal_sid, sqlserver.session_id, sqlserver.session_resource_group_id, sqlserver.session_server_principal_name, sqlserver.transaction_id, sqlserver.transaction_sequence)
WHERE 
)
 
