-- Event Session DDL autogenerated using ConvertTraceToExtendedEvent procedure.
-- (c) 2009 Microsoft Corporation.
CREATE EVENT SESSION XE_TraceStandardTemplate
ON SERVER
ADD EVENT sqlserver.existing_connection
(ACTION (sqlserver.client_app_name, sqlserver.client_pid, sqlserver.nt_username, sqlserver.server_principal_name, sqlserver.session_id)
WHERE sqlserver.client_app_name NOT LIKE '%SQL Server Profiler - 1888e114-0284-43e8-8f89-b5c757b86f6d%'
)
,
ADD EVENT sqlserver.login
(ACTION (sqlserver.client_app_name, sqlserver.client_pid, sqlserver.nt_username, sqlserver.server_principal_name, sqlserver.session_id)
WHERE sqlserver.client_app_name NOT LIKE '%SQL Server Profiler - 1888e114-0284-43e8-8f89-b5c757b86f6d%'
)
,
ADD EVENT sqlserver.logout
(ACTION (sqlserver.client_app_name, sqlserver.client_pid, sqlserver.nt_username, sqlserver.server_principal_name, sqlserver.session_id)
WHERE sqlserver.client_app_name NOT LIKE '%SQL Server Profiler - 1888e114-0284-43e8-8f89-b5c757b86f6d%'
)
,
ADD EVENT sqlserver.rpc_completed
(ACTION (sqlserver.client_app_name, sqlserver.client_pid, sqlserver.nt_username, sqlserver.server_principal_name, sqlserver.session_id)
WHERE sqlserver.client_app_name NOT LIKE '%SQL Server Profiler - 1888e114-0284-43e8-8f89-b5c757b86f6d%'
)
,
ADD EVENT sqlserver.sql_batch_completed
(ACTION (sqlserver.client_app_name, sqlserver.client_pid, sqlserver.nt_username, sqlserver.server_principal_name, sqlserver.session_id)
WHERE sqlserver.client_app_name NOT LIKE '%SQL Server Profiler - 1888e114-0284-43e8-8f89-b5c757b86f6d%'
)
,
ADD EVENT sqlserver.sql_batch_starting
(ACTION (sqlserver.client_app_name, sqlserver.client_pid, sqlserver.nt_username, sqlserver.server_principal_name, sqlserver.session_id)
WHERE sqlserver.client_app_name NOT LIKE '%SQL Server Profiler - 1888e114-0284-43e8-8f89-b5c757b86f6d%'
)
 
