------------------------------------------------------------------------
--
-- Script:			01.creazione-salesdb.sql
-- Author:			Gianluca Hotz (Solid Quality Learning)
-- Credits:
-- Copyright:		Attribution-NonCommercial-ShareAlike 2.5
-- Version:			SQL Server 2000/2005/2008
--
-- Default paths:	c:\temp
--
-- Lo scopo di questo script e' di generare il database di prova che
-- sara' utilizzato in alcuni dei successivi script.
-- 
-- Modificare i percorsi sopra elencati coerentemente con quelli
-- della propria installazione.
--
------------------------------------------------------------------------


------------------------------------------------------------------------
-- Cambiamo contesto.
------------------------------------------------------------------------
USE master
GO

------------------------------------------------------------------------
-- Creazione del database
------------------------------------------------------------------------
IF EXISTS(SELECT * FROM sys.databases WHERE name = 'SalesDB')
		DROP DATABASE SalesDB
GO

CREATE DATABASE SalesDB
ON PRIMARY (
	NAME		= 'SalesDB_mdf'
,	FILENAME	= 'c:\temp\SalesDB.mdf'
,	SIZE		= 5MB
,	MAXSIZE		= 100MB
,	FILEGROWTH	= 5MB
)
LOG ON (
	NAME		= 'SalesDB_log'
,	FILENAME	= 'c:\temp\SalesDB.ldf'
,	SIZE		= 700MB
,	MAXSIZE		= 2000MB
,	FILEGROWTH	= 100MB
)
GO

ALTER DATABASE	SalesDB
ADD FILEGROUP	DEFDATA
GO

ALTER DATABASE	SalesDB
ADD FILE (
	NAME		= 'SalesDB_defaultdata'
,	FILENAME	= 'c:\temp\SalesDB_defaultdata.mdf'
,	SIZE		= 5MB
,	MAXSIZE		= 100MB
,	FILEGROWTH	= 5MB
)
TO FILEGROUP DEFDATA
GO

ALTER DATABASE	SalesDB
ADD FILEGROUP	CUSTOMERS
GO

ALTER DATABASE	SalesDB
ADD FILE (
	NAME		= 'SalesDB_customers'
,	FILENAME	= 'c:\temp\SalesDB_customers.mdf'
,	SIZE		= 5MB
,	MAXSIZE		= 100MB
,	FILEGROWTH	= 5MB
)
TO FILEGROUP CUSTOMERS
GO

ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG01
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG01_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG01_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG01
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG01_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG01_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG01
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG01_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG01_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG01
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG02
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG02_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG02_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG02
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG02_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG02_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG02
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG02_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG02_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG02
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG03
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG03_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG03_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG03
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG03_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG03_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG03
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG03_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG03_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG03
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG04
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG04_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG04_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG04
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG04_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG04_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG04
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG04_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG04_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG04
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG05
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG05_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG05_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG05
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG05_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG05_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG05
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG05_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG05_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG05
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG06
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG06_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG06_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG06
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG06_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG06_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG06
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG06_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG06_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG06
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG07
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG07_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG07_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG07
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG07_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG07_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG07
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG07_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG07_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG07
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG08
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG08_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG08_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG08
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG08_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG08_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG08
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG08_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG08_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG08
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG09
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG09_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG09_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG09
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG09_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG09_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG09
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG09_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG09_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG09
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG10
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG10_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG10_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG10
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG10_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG10_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG10
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG10_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG10_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG10
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG11
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG11_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG11_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG11
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG11_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG11_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG11
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG11_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG11_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG11
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG12
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG12_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG12_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG12
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG12_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG12_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG12
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG12_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG12_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG12
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG13
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG13_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG13_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG13
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG13_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG13_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG13
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG13_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG13_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG13
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG14
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG14_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG14_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG14
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG14_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG14_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG14
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG14_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG14_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG14
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG15
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG15_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG15_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG15
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG15_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG15_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG15
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG15_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG15_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG15
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG16
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG16_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG16_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG16
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG16_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG16_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG16
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG16_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG16_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG16
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG17
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG17_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG17_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG17
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG17_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG17_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG17
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG17_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG17_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG17
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG18
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG18_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG18_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG18
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG18_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG18_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG18
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG18_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG18_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG18
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG19
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG19_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG19_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG19
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG19_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG19_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG19
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG19_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG19_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG19
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG20
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG20_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG20_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG20
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG20_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG20_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG20
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG20_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG20_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG20
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG21
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG21_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG21_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG21
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG21_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG21_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG21
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG21_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG21_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG21
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG22
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG22_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG22_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG22
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG22_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG22_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG22
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG22_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG22_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG22
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG23
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG23_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG23_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG23
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG23_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG23_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG23
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG23_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG23_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG23
ALTER DATABASE SalesDB ADD FILEGROUP OrdersFG24
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG24_FN01'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG24_FN01.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG24
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG24_FN02'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG24_FN02.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG24
ALTER DATABASE SalesDB
ADD FILE (
	NAME = 'SalesDB_OrdersFG24_FN03'
,	FILENAME = 'c:\temp\SalesDB_OrdersFG24_FN03.ndf'
,	SIZE = 20MB
,	MAXSIZE = 100MB
,	FILEGROWTH = 10MB
) TO FILEGROUP OrdersFG24
GO

------------------------------------------------------------------------
-- Impostazione Filegroup di default.
------------------------------------------------------------------------
ALTER DATABASE SalesDB MODIFY FILEGROUP DEFDATA DEFAULT
GO
