SELECT DISTINCT CASE WHEN DET.PRGRGFCEXT = 90 THEN -1 ELSE DET.PRGRGFCEXT END as Ordina,
	ISNULL(TES.IMRIMFC,0) as IMRIMFC, TES.CDTPFC as TipoFoglio, 'FE' as Costante, TES.CDISTCOLL as Codage,
	DET.nufc as NuFcExample, DET.NUFCEXT as NumfcExt, TES.DTFC as Datafc,  ISNULL(DET.PRGRGFCEXT,0) as Rigafc,
	DET.IDMOV as Nucon, DET.CDCAUSMOV as Tipop, ISNULL(TES.FLQUADRIM,'N') as FLQUADRIM, 
	CASE WHEN DET.CDCAUSMOV IN ('SQ','RP','IS','RS') THEN (-1*DET.IMAVERE) ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DG') THEN 0 ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DP') THEN (DET.IMDARE +(-1*DET.IMAVERE)) ELSE  DET.IMDARE END END END as Impdare,
	CASE WHEN DET.CDCAUSMOV IN ('SQ','RP','IS','RS') THEN (-1*DET.IMDARE) ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DP') THEN 0 ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DG') THEN (DET.IMAVERE +(-1*DET.IMDARE)) ELSE  DET.IMAVERE END END END as Impavere,
	CASE WHEN NOT EXISTS(
		SELECT 1 FROM SVGES020 A (NOLOCK) WHERE A.CDISTPROPR = DET.CDISTPROPR AND A.NUFC = DET.NUFC AND A.PRGRGFC > DET.PRGRGFC AND A.CDISTGEST = DET.CDISTGEST)
		THEN 'U'
		ELSE CASE WHEN NOT EXISTS(
			SELECT 1 FROM SVGES020 A (NOLOCK) WHERE A.CDISTPROPR = DET.CDISTPROPR AND A.NUFC = DET.NUFC AND A.PRGRGFC < DET.PRGRGFC AND A.CDISTGEST = DET.CDISTGEST)
		THEN 'P' ELSE '' END END as tipoDett, '' as Produt,
	'' as Ramo, '' as Nupol, '' as Agsin, '' as Esersin, '' as Nusin, '' as Nome, TES.DTFC as Datainc, TES.DTFC as Dataeff,
	'' as Mezzopag, '' as CodProd,  ' ' as Tipoincasso, 'X' as Tappo, 'RN' as TipoRiga, TES.DTCONTFC, '' as CDTPPNA, NULL AS PRGMOV, DET.TRANSID 
FROM SVGES011 TES (NOLOCK)
INNER JOIN SVGES020 DET (NOLOCK) ON TES.CDISTPROPR = DET.CDISTPROPR AND TES.CDISTGEST = DET.CDISTGEST AND DET.PRGRGFCEXT IN (90,97)
	AND TES.CDTPFC = DET.CDTPFC AND TES.CDISTCOLL = DET.CDISTCOLL AND TES.NUFC = DET.NUFC AND TES.CDSTFC = 'C'
WHERE TES.CDISTPROPR = @cdistpropr AND TES.DTCONTFC BETWEEN @datada AND @dataa AND TES.CDISTGEST = @cdistgest
        AND DET.PRGRGFCEXT IS NOT NULL
UNION ALL
--- CASO PNA ---
SELECT DISTINCT CASE WHEN DET.PRGRGFCEXT = 90 THEN -1 ELSE DET.PRGRGFCEXT END as Ordina,
	ISNULL(TES.IMRIMFC,0) as IMRIMFC, TES.CDTPFC as TipoFoglio, 'FE' as Costante, TES.CDISTCOLL as Codage,
	DET.nufc as NuFcExample, DET.NUFCEXT as NumfcExt, TES.DTFC as Datafc,  ISNULL(DET.PRGRGFCEXT,0) as Rigafc,
	DET.IDMOV as Nucon, DET.CDCAUSMOV as Tipop, ISNULL(TES.FLQUADRIM,'N') as FLQUADRIM,
	CASE WHEN DET.CDCAUSMOV IN ('SQ','RP','IS','RS') THEN (-1*DET.IMAVERE) ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DG') THEN 0 ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DP') THEN (DET.IMDARE +(-1*DET.IMAVERE)) ELSE  DET.IMDARE END END END as Impdare,
	CASE WHEN DET.CDCAUSMOV IN ('SQ','RP','IS','RS') THEN (-1*DET.IMDARE) ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DP') THEN 0 ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DG') THEN (DET.IMAVERE +(-1*DET.IMDARE)) ELSE  DET.IMAVERE END END END as Impavere,
	CASE WHEN NOT EXISTS(
		SELECT 1 FROM SVGES020 A (NOLOCK) WHERE A.CDISTPROPR = DET.CDISTPROPR AND A.NUFC = DET.NUFC AND A.PRGRGFC > DET.PRGRGFC AND A.CDISTGEST = DET.CDISTGEST)
		THEN 'U'
		ELSE CASE WHEN NOT EXISTS(
			SELECT 1 FROM SVGES020 A (NOLOCK) WHERE A.CDISTPROPR = DET.CDISTPROPR AND A.NUFC = DET.NUFC AND A.PRGRGFC < DET.PRGRGFC AND A.CDISTGEST = PNA.CDISTGEST)
		THEN 'P' ELSE '' END END as tipoDett, PNA.CDUTENTE as Produt,
	'' as Ramo, ISNULL(PNA.NUPOLIZ,'') as Nupol, '' as Agsin, '' as Esersin, '' as Nusin,
	UPPER(COALESCE(LTRIM(ISNULL(NULLIF(SOG.DSCOGNOME,''),'') + ' ' + SOG.DSNOME),PNA.DSPNA,'')) as Nome,
	COALESCE(PNA.DTCONTPNA,PNA.DTEFFPNA,TES.DTFC) as Datainc,
	COALESCE(PNA.DTEFFPNA,PNA.DTCONTPNA,TES.DTFC) as Dataeff,
	CASE ISNULL(PNA.CDMOPAG,'') WHEN 'S' THEN 'A' WHEN 'E' THEN 'B' WHEN 'C' THEN 'C' WHEN 'A' THEN 'A' WHEN 'T' THEN 'T' ELSE '' END as Mezzopag,
	'' as CodProd,  ' ' as Tipoincasso, 'X' as Tappo, 'RN' as TipoRiga, TES.DTCONTFC, PNA.CDTPPNA, PNA.PRGPNA AS PRGMOV, DET.TRANSID 
FROM SVGES011 TES (NOLOCK)
INNER JOIN SVGES020 DET (NOLOCK) ON TES.CDISTPROPR = DET.CDISTPROPR AND TES.CDISTGEST = DET.CDISTGEST
	AND TES.CDTPFC = DET.CDTPFC AND TES.CDISTCOLL = DET.CDISTCOLL AND TES.NUFC = DET.NUFC AND TES.CDSTFC = 'C'
INNER JOIN SVGES218 PNA (NOLOCK) ON DET.IDMOV = PNA.IDPNA AND PNA.CDISTPROPR = DET.CDISTPROPR --AND DET.CDTPMOV = 'P'
LEFT JOIN SVGES005 SOG (NOLOCK) ON SOG.CDISTPROPR = PNA.CDISTPROPR AND SOG.NUSOGG = PNA.NUSOGGCONTR
WHERE TES.CDISTPROPR = @cdistpropr AND TES.DTCONTFC BETWEEN @datada AND @dataa AND TES.CDISTGEST = @cdistgest
 AND DET.PRGRGFCEXT IS NOT NULL
-- CASO INCASSI --
UNION ALL
SELECT DISTINCT CASE WHEN DET.PRGRGFCEXT = 90 THEN -1 ELSE DET.PRGRGFCEXT END as Ordina,
	ISNULL(TES.IMRIMFC,0) as IMRIMFC, TES.CDTPFC as TipoFoglio, 'FE' as Costante, TES.CDISTCOLL as Codage,
	DET.nufc as NuFcExample, DET.NUFCEXT as NumfcExt, TES.DTFC as Datafc,  ISNULL(DET.PRGRGFCEXT,0) as Rigafc,
	DET.IDMOV as Nucon, DET.CDCAUSMOV as Tipop, ISNULL(TES.FLQUADRIM,'N') as FLQUADRIM,
	CASE WHEN DET.CDCAUSMOV IN ('SQ','RP','IS','RS') THEN (-1*DET.IMAVERE) ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DG') THEN 0 ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DP') THEN (DET.IMDARE +(-1*DET.IMAVERE)) ELSE  DET.IMDARE END END END as Impdare,
	CASE WHEN DET.CDCAUSMOV IN ('SQ','RP','IS','RS') THEN (-1*DET.IMDARE) ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DP') THEN 0 ELSE 
        CASE WHEN DET.CDCAUSMOV IN ('DG') THEN (DET.IMAVERE +(-1*DET.IMDARE)) ELSE  DET.IMAVERE END END END as Impavere,
	CASE WHEN NOT EXISTS(
		SELECT 1 FROM SVGES020 A (NOLOCK) WHERE A.CDISTPROPR = DET.CDISTPROPR AND A.NUFC = DET.NUFC AND A.PRGRGFC > DET.PRGRGFC AND A.CDISTGEST = DET.CDISTGEST)
		THEN 'U'
		ELSE CASE WHEN NOT EXISTS(
			SELECT 1 FROM SVGES020 A (NOLOCK) WHERE A.CDISTPROPR = DET.CDISTPROPR AND A.NUFC = DET.NUFC AND A.PRGRGFC < DET.PRGRGFC AND A.CDISTGEST = DET.CDISTGEST)
		THEN 'P' ELSE '' END END as tipoDett, POL.CDUTENTE as Produt,
	ISNULL(CAST(POL.CDRAMOPOLIZ as varchar(10)),'') as Ramo, ISNULL(POL.NUPOLIZ,'') as Nupol, '' as Agsin, '' as Esersin, '' as Nusin,
	UPPER(ISNULL(LTRIM(SOG.DSCOGNOME) + ' ' + SOG.DSNOME,'')) as Nome,
	COALESCE(INC.DTCONTADD,INC.DTCONTACC,INC.DTEFFMOV,INC.DTMOVIM,TES.DTFC) as Datainc,
	COALESCE(INC.DTEFFMOV,INC.DTCONTADD,INC.DTCONTACC,INC.DTMOVIM,TES.DTFC) as Dataeff,
	CASE ISNULL(INC.CDMODPAGADD,'') WHEN 'S' THEN 'A' WHEN 'E' THEN 'B' WHEN 'C' THEN 'C' WHEN 'A' THEN 'A' WHEN 'T' THEN 'T' ELSE '' END as Mezzopag,
	ISNULL(POL.CDPROD,'') as CodProd,  ' ' as Tipoincasso, 'X' as Tappo, 'RN' as TipoRiga, TES.DTCONTFC, '' as CDTPPNA, INC.PRGMOV, DET.TRANSID 
FROM SVGES011 TES (NOLOCK)
INNER JOIN SVGES020 DET (NOLOCK) ON TES.CDISTPROPR = DET.CDISTPROPR AND TES.CDISTGEST = DET.CDISTGEST
	AND TES.CDTPFC = DET.CDTPFC AND TES.CDISTCOLL = DET.CDISTCOLL AND TES.NUFC = DET.NUFC AND TES.CDSTFC = 'C'
INNER JOIN SVGES117 INC (NOLOCK) ON INC.CDISTPROPR = DET.CDISTPROPR AND DET.CDTPMOV = 'I' 
 AND (( DET.IDMOV = INC.IDMOVADD AND INC.PRGMOV = (SELECT MAX(X.PRGMOV) FROM SVGES117 (NOLOCK) X where X.CDISTPROPR=DET.CDISTPROPR AND X.IDMOVADD =DET.IDMOV)) 
   OR (INC.CDSTMOV='N' AND DET.IDMOV = INC.IDMOVRIMB )) 
INNER JOIN SVGES108 POL (NOLOCK) ON POL.NURELAZ = INC.NURELAZ AND POL.CDISTPROPR = DET.CDISTPROPR
INNER JOIN SVGES102 CNT (NOLOCK) ON INC.CDISTPROPR = CNT.CDISTPROPR AND INC.NURELAZ = CNT.NURELAZ AND DET.CDTPMOV = 'I'
INNER JOIN SVGES005 SOG (NOLOCK) ON SOG.CDISTPROPR = CNT.CDISTPROPR AND SOG.NUSOGG = CNT.NUSOGG
WHERE TES.CDISTPROPR = @cdistpropr AND TES.DTCONTFC BETWEEN @datada AND @dataa AND TES.CDISTGEST = @cdistgest
 AND DET.PRGRGFCEXT IS NOT NULL
ORDER BY tipofoglio,codage,Datafc, nufcExample,NumfcExt, Ordina
